using Statistics

x = collect(1.0:20.0)
y = 2.0 .* x .+ randn(length(x))

# Write a minimal SVG so the test doesn't need Plots.jl
open("figures/fig1.pdf", "w") do io
    println(io, "%PDF-1.4 stub — generated by analysis.jl")
    println(io, "mean_x=$(mean(x)) mean_y=$(mean(y))")
end
