import math
import statistics

x = list(range(1, 21))
y = [2.0 * xi + (xi % 3 - 1) * 0.5 for xi in x]

with open("figures/fig1.pdf", "w") as f:
    f.write("%PDF-1.4 stub — generated by analysis.py\n")
    f.write(f"mean_x={statistics.mean(x)} mean_y={statistics.mean(y):.4f}\n")
